#server:
#  port: 8888
#  servlet:
#   context-path: /spring-boot-demo # 访问地址：http://localhost:8888/spring-boot-demo
#  tomcat:
#    uri-encoding: UTF-8
##  session:
##    timeout:
#
##=====================================  mysql配置  =============================
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update # create (自动创建表,要先创建类,每次都是先删再创建) update：如果表存在则不创建，只在第一次初始化时创建表
#      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#    show-sql: true
#引入日志配置文件
#=====================================  log  =============================
logging:
  file: my.log
#  level:
#    root: info
#    com.bestvike: debug
#    org.springframework.security: warn


